version: '2'
#membuat service
services :
#membuat service : item-app
  item-app:
  #Menggunakan image item-app dari github packages
    image: ghcr.io/adinda345/item-app:v1
    #menerapkan restart policy, agar container selalu restart ketika berhenti
    restart: always
    #Melakukan port mapping agar dapat diakses dari port 80 di host.
    ports:
      - "80:8080"
      #Pastikan item-app hanya berjalan setelah item-db diluncurkan.
    depends_on:
      - item-db
#membuat service: item-db  
  item-db:
  #Menggunakan image mongo:3 dari Docker Hub.
    image: mongo:3
    #menerapkan restart policy, agar container selalu restart ketika berhenti
    restart: always
    #Memakai volume bernama app-db dengan target /data/db di container.
    volumes:
      - app-db:/data/db
#membuat volume
volumes:
  app-db: